In [1]:
import torch
import numpy as np

In [2]:
import torch.nn as nn

In [3]:
Inputs=np.array(
                [[73,67,43], [91,88,64],[87,134,58],
                 [102,43,37], [69,96,70], [73,67,43],
                 [91,88,64],  [87,134,58],[102,43,37],
                 [69,96,70], [73,67,43], [91,88,64],
                 [87,134,58], [102,43,37], [69,96,70]
                ], dtype='float32'
)

Targets=np.array([
                [56,70], [81,101], [119,133],
                [22,37], [103,119], [56,70],
                [81,101], [119,133], [22,37],
                [103,119], [56,70], [81,101],
                [119,133], [22,37], [103,119]
],dtype='float32')

In [4]:
inputs=torch.from_numpy(Inputs)
targets=torch.from_numpy(Targets)

In [5]:
from torch.utils.data import TensorDataset

In [6]:
#define dataset
train_ds=TensorDataset(inputs,targets)

In [7]:
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
from torch.utils.data import DataLoader

In [9]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [12]:
for xb,yb in train_ds:
    print(xb)
    print(yb)

tensor([73., 67., 43.])
tensor([56., 70.])
tensor([91., 88., 64.])
tensor([ 81., 101.])
tensor([ 87., 134.,  58.])
tensor([119., 133.])
tensor([102.,  43.,  37.])
tensor([22., 37.])
tensor([69., 96., 70.])
tensor([103., 119.])


In [13]:
#Define model

model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5142,  0.0513,  0.3743],
        [-0.1963,  0.3037,  0.3643]], requires_grad=True)
Parameter containing:
tensor([ 0.2173, -0.3164], requires_grad=True)


In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5142,  0.0513,  0.3743],
         [-0.1963,  0.3037,  0.3643]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2173, -0.3164], requires_grad=True)]

In [17]:
#We can use the model to generate predictions in the same way as before.
preds=model(inputs)
preds

tensor([[57.2840, 21.3668],
        [75.4765, 31.8619],
        [73.5322, 44.4330],
        [68.7201,  6.1973],
        [66.8196, 40.7973]], grad_fn=<AddmmBackward>)

In [18]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [19]:
#Import nn.functional
import torch.nn.functional as F

#Define loss function
loss_fn=F.mse_loss

In [21]:
loss=loss_fn(preds,targets)
loss

tensor(2764.5103, grad_fn=<MseLossBackward>)

In [23]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [30]:
def fit(num_epoch,model,loss_fn,opt):
    
    #Repeat for number of epochs given
    for epoch in range(num_epoch):
        
        #Train with batches of the data
        for xb,yb in train_dl:
            
            #generate predictions
            preds=model(xb)
            
            #generate loss function
            loss=loss_fn(preds,yb)
            
            #compute gradient
            loss.backward()
            
            #update parameters using gtadients
            opt.step()
            
            #reset gradient to zero
            opt.zero_grad()
            
        print("Epoch: {}   Loss: {}". format(epoch, loss.item()) )

In [32]:
fit(1000,model,loss_fn,opt)

Epoch: 0   Loss: 374.47357177734375
Epoch: 1   Loss: 369.8227844238281
Epoch: 2   Loss: 365.23162841796875
Epoch: 3   Loss: 360.69903564453125
Epoch: 4   Loss: 356.2242431640625
Epoch: 5   Loss: 351.80596923828125
Epoch: 6   Loss: 347.44366455078125
Epoch: 7   Loss: 343.13641357421875
Epoch: 8   Loss: 338.8834533691406
Epoch: 9   Loss: 334.6842346191406
Epoch: 10   Loss: 330.5379943847656
Epoch: 11   Loss: 326.44384765625
Epoch: 12   Loss: 322.40142822265625
Epoch: 13   Loss: 318.4099426269531
Epoch: 14   Loss: 314.468505859375
Epoch: 15   Loss: 310.576904296875
Epoch: 16   Loss: 306.73431396484375
Epoch: 17   Loss: 302.9400634765625
Epoch: 18   Loss: 299.193603515625
Epoch: 19   Loss: 295.4942932128906
Epoch: 20   Loss: 291.8415832519531
Epoch: 21   Loss: 288.2348327636719
Epoch: 22   Loss: 284.6734924316406
Epoch: 23   Loss: 281.1569519042969
Epoch: 24   Loss: 277.6848449707031
Epoch: 25   Loss: 274.2563781738281
Epoch: 26   Loss: 270.8709716796875
Epoch: 27   Loss: 267.5282897949219

In [33]:
preds=model(inputs)

In [34]:
preds

tensor([[ 57.2756,  70.3683],
        [ 81.6816,  99.8089],
        [119.7109, 134.8211],
        [ 21.4578,  37.5748],
        [100.8286, 117.2509]], grad_fn=<AddmmBackward>)

In [35]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])