In [1]:
import torch

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype


torch.float32

In [6]:
t1.type

<function Tensor.type>

In [8]:
t2=torch.tensor([05.00,3,34.])
t2

tensor([ 5.,  3., 34.])

In [9]:
t2.shape

torch.Size([3])

In [11]:
t3=torch.tensor([[1.0,3.0],[2.0,4.0],[4.0,5.0]])
t3

tensor([[1., 3.],
        [2., 4.],
        [4., 5.]])

In [12]:
t3.shape

torch.Size([3, 2])

In [21]:
t4=torch.tensor ([
    [[1,3,4],[2,4,5]],
    [[5,4,4],[4,6,5]],
    [[7,2,5],[3,5,5]]
])
t4

tensor([[[1, 3, 4],
         [2, 4, 5]],

        [[5, 4, 4],
         [4, 6, 5]],

        [[7, 2, 5],
         [3, 5, 5]]])

In [20]:
t4.shape

torch.Size([3, 2, 3])

In [16]:
t4.dtype

torch.int64

In [25]:
x=torch.tensor([3.0])
w=torch.tensor([4.0],requires_grad=True)
b=torch.tensor([5.0],requires_grad=True)

In [26]:
y=w*x+b
y

tensor([17.], grad_fn=<AddBackward0>)

In [27]:
y.backward()

In [29]:
print("dy/dx =",x.grad)
print("dy/dw =",w.grad)
print("dy/db =",b.grad)

dy/dx = None
dy/dw = tensor([3.])
dy/db = tensor([1.])


In [30]:
import numpy as np

In [31]:
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [32]:
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [33]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [34]:
y=torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [36]:
#Convert torch to numpy
print(y.dtype)
z=y.numpy()
print(z.dtype)

torch.int32
int32
