In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

In [4]:
# Convert 2D List to 2D Tensor
two_d_list=[[11,12,13,14],[21,22,23,24],[31,32,33,34]]
print("2D list:", two_d_list)
two_d_tensor=torch.tensor(two_d_list)
print("2D list:", two_d_tensor)

2D list: [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
2D list: tensor([[11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]])


In [6]:
# Try tensor_obj.ndimension(), tensor_obj.shape, tensor_obj.size()

print("Dimension of tensor:", two_d_tensor.ndimension())
print("shape of tesnor:", two_d_tensor.shape)
print("Size of tesnor:", two_d_tensor.size())
print("Type of tensor:", two_d_tensor.type())
print("Dtype of tesnor:", two_d_tensor.dtype)

Dimension of tensor: 2
shape of tesnor: torch.Size([3, 4])
Size of tesnor: torch.Size([3, 4])
Type of tensor: torch.LongTensor
Dtype of tesnor: torch.int64


In [10]:
# Convert tensor to numpy array; Convert numpy array to tensor
convert_to_numpy=two_d_tensor.numpy()
print("Tensor -> Numpy Array:")
print("The numpy array after converting: ", convert_to_numpy)
print("Type after converting: ", convert_to_numpy.dtype)

#Converting back to tesnor
back_to_tensor=torch.from_numpy(convert_to_numpy)
print("\n\n Numpy Array --> Tensor")
print("The numpy array after converting: ", back_to_tensor)
print("Type after converting: ", back_to_tensor.dtype)



Tensor -> Numpy Array:
The numpy array after converting:  [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Type after converting:  int64


 Numpy Array --> Tensor
The numpy array after converting:  tensor([[11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]])
Type after converting:  torch.int64


In [19]:
# Try to convert the Panda Dataframe to tensor

dataframe=pd.DataFrame({"a":[11,21,31],"b":[12,22,32],"c":[13,23,33]})
print("Dataframe")
print("Dataframe value:", dataframe)
print("Dataframe type:", dataframe.values.dtype)

new_tensor=torch.from_numpy(dataframe.values)
print("\n\nTensor")
print("Tensor value:", new_tensor)
print("new_tensor type:", new_tensor.dtype)


Dataframe
Dataframe value:     a   b   c
0  11  12  13
1  21  22  23
2  31  32  33
Dataframe type: int64


Tensor
Tensor value: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
new_tensor type: torch.int64


## Indexing and Slicing

In [22]:
tensor_example=torch.tensor([[11,12,13],[21,22,23],[31,32,33]])
print("Tesnor:", tensor_example)

print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2])
print("What is the value on 2nd-row 3rd-column? ",tensor_example[1,2])

Tesnor: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
What is the value on 2nd-row 3rd-column?  tensor(23)
What is the value on 2nd-row 3rd-column?  tensor(23)


In [45]:
# Give an idea on tensor_obj[number: number][number]

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("Tensor:", tensor_example)
sliced_tensor_example =tensor_example[1:3]
print("Result after tensor_example[1:3]: ",sliced_tensor_example)
print("Dimension after tensor_example[1:3]: ", sliced_tensor_example.ndimension())
print("================================================")
print("2. Pick an index on sliced_tensor_example: ")
print("Result after sliced_tensor_example[1]: ", tensor_example[1])
print("Dimension after sliced_tensor_example[1]: ", tensor_example[1].ndimension())
print("Shape after sliced_tensor_example[1]: ", tensor_example[1].shape)
print("================================================")
print("3. Combine these step together:")
print("Result: ", tensor_example[1:3][1])
print("Dimension: ", tensor_example[1:3][1].ndimension())
print("Shape after sliced_tensor_example[1]: ", tensor_example[1:3][1].shape)


Tensor: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Result after tensor_example[1:3]:  tensor([[21, 22, 23],
        [31, 32, 33]])
Dimension after tensor_example[1:3]:  2
2. Pick an index on sliced_tensor_example: 
Result after sliced_tensor_example[1]:  tensor([21, 22, 23])
Dimension after sliced_tensor_example[1]:  1
Shape after sliced_tensor_example[1]:  torch.Size([3])
3. Combine these step together:
Result:  tensor([31, 32, 33])
Dimension:  1
Shape after sliced_tensor_example[1]:  torch.Size([3])


## Tensor Operations

In [49]:
X = torch.tensor([[1, 0],[0, 1]]) 
Y = torch.tensor([[2, 1],[1, 2]])

x_plus_Y=X+Y
print(x_plus_Y)

tensor([[3, 1],
        [1, 3]])


In [50]:
Y = torch.tensor([[2, 1], [1, 2]]) 
two_Y = 2 * Y
print("The result of 2Y: ", two_Y)

The result of 2Y:  tensor([[4, 2],
        [2, 4]])


In [51]:
# Calculate [[1, 0], [0, 1]] * [[2, 1], [1, 2]]

X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print("The result of X * Y: ", X_times_Y)

The result of X * Y:  tensor([[2, 0],
        [0, 2]])


In [52]:
# Calculate [[0, 1, 1], [1, 0, 1]] * [[1, 1], [1, 1], [-1, 1]]

A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print("The result of A * B: ", A_times_B)

The result of A * B:  tensor([[0, 2],
        [0, 2]])
