In [1]:
#pip install torch

In [2]:
# These are the libraries will be used for this lab.
import torch 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline  

In [3]:
#Check PyTorch version:
torch.__version__

'1.8.1+cpu'

In [4]:
# Convert a integer list with length 5 to a tensor

ints_to_tensor=torch.tensor([0,1,2,3,4,5])
print(ints_to_tensor.dtype)
print(ints_to_tensor.type())
print(ints_to_tensor.shape)


torch.int64
torch.LongTensor
torch.Size([6])


In [5]:
# Convert a float list with length 5 to a tensor

float_to_tensor = torch.tensor([1.1,1.2,4.3])
print(float_to_tensor.type())
print(float_to_tensor.dtype)

torch.FloatTensor
torch.float32


In [6]:
#The float list is converted to a float tensor.

list_floats=[0.0, 1.0, 2.0, 3.0, 4.0]
float_int_tensor = torch.tensor(list_floats)
print(float_int_tensor.type())
print(float_int_tensor.dtype)
float_int_tensor = torch.tensor(list_floats,dtype=torch.int64)
print(float_int_tensor.type())
print(float_int_tensor.dtype)

torch.FloatTensor
torch.float32
torch.LongTensor
torch.int64


In [19]:
# Convert a integer list with length 5 to float tensor

new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])
print(new_float_tensor.type())
print(new_float_tensor.dtype)
new_float_tensors = torch.tensor([0, 1, 2, 3, 4],dtype=torch.float32)
print("The type of the new_float_tensor:", new_float_tensors.type())
print("The type of the new_float_tensor:", new_float_tensors.dtype)

torch.FloatTensor
torch.float32
The type of the new_float_tensor: torch.FloatTensor
The type of the new_float_tensor: torch.float32


In [20]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])

In [21]:
new_float_tensor.dtype

torch.float32

In [22]:
old_int_tensor = torch.tensor([0, 1, 2, 3, 4])
new_int_tensor=old_int_tensor.type(torch.FloatTensor)
new_int_tensor.dtype

torch.float32

In [23]:
# Convert a tensor to a numpy array
back_to_numpy =new_int_tensor.numpy()
print(back_to_numpy)
print(back_to_numpy.dtype)
print(type(back_to_numpy))

[0. 1. 2. 3. 4.]
float32
<class 'numpy.ndarray'>


In [25]:
# Convert a panda series to a tensor

pandas_series=pd.Series([0.1, 2, 0.3, 10.1])
new_tensor=torch.from_numpy(pandas_series.values)
print(new_tensor)
print(new_tensor.type())
print(new_tensor.dtype)

tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
torch.DoubleTensor
torch.float64


In [29]:
this_tensor=torch.tensor([0,1, 2,3],dtype=torch.float32) 
this_tensor

tensor([0., 1., 2., 3.])

In [36]:
torch_to_list=this_tensor.tolist()
torch_to_list

[0.0, 1.0, 2.0, 3.0]

In [40]:
your_tensor=[1, 2, 3, 4, 5]
your_tensor=torch.tensor(your_tensor)
your_tensor

tensor([1, 2, 3, 4, 5])

In [43]:
# Indexing and slicing of tensor
Index_tensor=torch.tensor([1,2,3,4,5])
print("0 th element of tesnor:",Index_tensor[0])
print("1 st element of tesnor:",Index_tensor[1])
print("2 nd element of tesnor:",Index_tensor[2])
print("3 rd element of tesnor:",Index_tensor[3])
# slicing
print("Tensor slice:",Index_tensor[1:3])

0 th element of tesnor: tensor(1)
1 st element of tesnor: tensor(2)
2 nd element of tesnor: tensor(3)
3 rd element of tesnor: tensor(4)
Tensor slice: tensor([2, 3])


In [49]:
# A tensor for showing how to change value according to the index
tensor_for_change=torch.tensor([0,1,2,3,4,5])
print(tensor_for_change)
tensor_for_change[0]=100
print(tensor_for_change)
tensor_for_change[0:2]=torch.tensor([100,200])
print(tensor_for_change)

tensor([0, 1, 2, 3, 4, 5])
tensor([100,   1,   2,   3,   4,   5])
tensor([100, 200,   2,   3,   4,   5])


In [51]:
# Using variable to contain the selected index, and pass it to slice operation
print(tensor_for_change)
selected_indexes = [3, 4]
subset_tensor_sample = tensor_for_change[selected_indexes]
print("Subset:", subset_tensor_sample)

tensor([100, 200,   2,   3,   4,   5])
Subset: tensor([3, 4])


In [52]:
#Using variable to assign the value to the selected indexes
selected_indexes = [3, 4]
tensor_for_change[selected_indexes]=10000
print(tensor_for_change)

tensor([  100,   200,     2, 10000, 10000,     5])


In [55]:
# Practice: Change the values on index 3, 4, 7 to 0

practice_tensor = torch.tensor([2, 7, 3, 4, 6, 2, 3, 1, 2])
practice_tensor[[3,4,7]]=0
practice_tensor

tensor([2, 7, 3, 0, 0, 2, 3, 0, 2])

# Mean and Standard Deviation

In [59]:
math_tensor = torch.tensor([1.0, -1.0, 1, -1])
print("Tensor example: ", math_tensor)
print("Tensor mean: ", math_tensor.mean())
print("Tensor mean: ", math_tensor.std())

Tensor example:  tensor([ 1., -1.,  1., -1.])
Tensor mean:  tensor(0.)
Tensor mean:  tensor(1.1547)


# Max and Min

In [60]:
max_min_tensor = torch.tensor([1, 1, 3, 5, 5])
print("Tensor example:", max_min_tensor)
print("Min of tesnor:",max_min_tensor.min())
print("Max of tesnor:",max_min_tensor.max())

Tensor example: tensor([1, 1, 3, 5, 5])
Min of tesnor: tensor(1)
Max of tesnor: tensor(5)


# Sin

In [61]:
# Method for calculating the sin result of each element in the tensor

pi_tensor = torch.tensor([0, np.pi/2, np.pi])
sin = torch.sin(pi_tensor)
print("The sin result of pi_tensor: ", sin)

The sin result of pi_tensor:  tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])


In [62]:
pi_tensor.sin()

tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])

# Create Tensor by torch.linspace()

In [64]:
# try creating linspace for tensor
linespace_tensor=torch.linspace(-2,2,steps=5)
linespace_tensor

tensor([-2., -1.,  0.,  1.,  2.])

In [67]:
print(linespace_tensor.type())

torch.FloatTensor


In [65]:
len_9_tensor = torch.linspace(-2, 2, steps = 9)
print ("Second Try on linspace", len_9_tensor)

Second Try on linspace tensor([-2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,
         2.0000])


In [66]:
len_9_tensor.type()

'torch.FloatTensor'

In [69]:
import numpy as np
np.pi

3.141592653589793

In [70]:
my_tensor=torch.linspace(0,np.pi/2,steps=25)

In [71]:
my_tensor

tensor([0.0000, 0.0654, 0.1309, 0.1963, 0.2618, 0.3272, 0.3927, 0.4581, 0.5236,
        0.5890, 0.6545, 0.7199, 0.7854, 0.8508, 0.9163, 0.9817, 1.0472, 1.1126,
        1.1781, 1.2435, 1.3090, 1.3744, 1.4399, 1.5053, 1.5708])

In [73]:
print(my_tensor)
print(my_tensor.min())
print(my_tensor.max())
print(my_tensor.sin())
print(torch.sin(my_tensor))

tensor([0.0000, 0.0654, 0.1309, 0.1963, 0.2618, 0.3272, 0.3927, 0.4581, 0.5236,
        0.5890, 0.6545, 0.7199, 0.7854, 0.8508, 0.9163, 0.9817, 1.0472, 1.1126,
        1.1781, 1.2435, 1.3090, 1.3744, 1.4399, 1.5053, 1.5708])
tensor(0.)
tensor(1.5708)
tensor([0.0000, 0.0654, 0.1305, 0.1951, 0.2588, 0.3214, 0.3827, 0.4423, 0.5000,
        0.5556, 0.6088, 0.6593, 0.7071, 0.7518, 0.7934, 0.8315, 0.8660, 0.8969,
        0.9239, 0.9469, 0.9659, 0.9808, 0.9914, 0.9979, 1.0000])
tensor([0.0000, 0.0654, 0.1305, 0.1951, 0.2588, 0.3214, 0.3827, 0.4423, 0.5000,
        0.5556, 0.6088, 0.6593, 0.7071, 0.7518, 0.7934, 0.8315, 0.8660, 0.8969,
        0.9239, 0.9469, 0.9659, 0.9808, 0.9914, 0.9979, 1.0000])


In [74]:
# Create two sample tensors

u = torch.tensor([1, 0])
v = torch.tensor([0, 1])
w = u + v
print("The result tensor: ", w)

The result tensor:  tensor([1, 1])


In [75]:
# tensor + scalar

u = torch.tensor([1, 2, 3, -1])
v = u + 1
print ("Addition Result: ", v)

Addition Result:  tensor([2, 3, 4, 0])


In [76]:
# tensor * scalar

u = torch.tensor([1, 2])
v = 2 * u
print("The result of 2 * u: ", v)

The result of 2 * u:  tensor([2, 4])


In [77]:
# tensor * tensor

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
w = u * v
print ("The result of u * v", w)

The result of u * v tensor([3, 4])


In [78]:
# Calculate dot product of u, v

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])

print("Dot Product of u, v:", torch.dot(u,v))

Dot Product of u, v: tensor(7)
